### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by 425e0bbe** [ArachisH/Eavesdrop#2]
The project has very serious problems that are associated with a memory leak. For example: when youtube is visited, memory is used normally, but if you look at the video on xhamster then the proxy uses a lot of RAM, but the video is not displayed. The garbage collector does not help. I could not find out why this is happening and I ask you to help with this.

**Comment by ArachisH** [comment]
I'll... check it out...

**Comment by ArachisH** [comment]
Let me know if you still have problems with it, but I think I managed to fix the problem so far. The issue was that it was trying to store the whole video in memory *before* it sent the payload to the client, so the fix was to have it send the payload to the client in chunks(like it should have been doing).
