### ISSUE TITLE
External Proxying is not working for HTTPS

### ISSUE THREAD

**Issue by valloon427428** [ArachisH/Eavesdrop#29]
External Proxying is not working for HTTPS. I used http proxy with auth.
Here is my code:

```
Eavesdropper.Proxy = new WebProxy("http://proxyhost:port");
Eavesdropper.Proxy.Credentials = new NetworkCredential("username", "passw0rd!");
Eavesdropper.IsActingAsForwardingServer = true;
```

When I set my proxy on my Chrome Browser, and open HTTPS link, this page shows:
![image](https://github.com/user-attachments/assets/3daad87c-1c28-4a7c-a532-a1ace415da05)

HTTP is working fine, but HTTPS is not working. If I remove these code, it works quiet well. I also installed certificates with:
`bool success = Eavesdropper.CertProvider?.TryCreateTrustedRootCA("Eavesdrop");`

I am very interested in this project and this feature. I need help in this field. I am working on .NET 8. Thanks.

PS: NuGet v1.3.0 looks a little old than the develop branch.

**Comment by ArachisH** [comment]
I'm unable to replicate this issue using both the develop branch and the NuGet package version. Could you let me know which HTTP/S proxy provider you are using so that I may test against their service?

For context, I'm currently using the HTTP proxy tunnel provided through Ultra.cc, and I'm not getting a certificate invalid error as in the screenshot using my credentials. (IsActingAsForwardingServer = true & false)

The version of Chrome I'm using is 'Version 131.0.6778.109 (Official Build) (64-bit)', and running it using the .NET 8 runtime.

Could you let me know if you see 'Eavesdrop Root Certificate Authority' in:
Start > Manage user certificates > Trusted Root Certification Authorities > Certificates

If so, confirm that the expiration date of the certificate hasn't expired. The changes between the publicly released NuGet version and the develop branch are related to the certificate creation process, so perhaps allowing it to re-create the root certificate authority using the develop branch may help.

Otherwise, let me know which service provider you're using for proxying so I can take a further look.

**Comment by valloon427428** [comment]
Thanks for your reply. I tried on the other Proxy provider, and I works well. I found that some proxies does not accept HTTPS. 

And I have few more questions:
- May I change the certificate name? Currently "Eavesdrop" in the project.
- Is it necessary to install certificates when IsActingAsForwardingServer = true ?
Thanks

**Comment by ArachisH** [comment]
You can change the name of the certificate issuer 'O=', and the name of the root CA it generates by creating a new instance of the Certifier class, or if you're using the develop branch by using the 'TryCreateTrustedRootCA' method with the second parameter:

```csharp
// On v1.3.0
Eavesdropper.Certifier = new Certifier("Valloon"); // Generates 'Valloon Root Certificate Authority'
Eavesdropper.Certifier = new Certifier("Valloon", "Valloon Big Boss Certificate Authority");

// On 2.0.0
Eavesdropper.CertProvider?.TryCreateTrustedRootCA("Valloon");
Eavesdropper.CertProvider?.TryCreateTrustedRootCA("Valloon Big Boss Certificate Authority", "Valloon");
```

It is also **NOT** necessary to install a root certificate on the listening machine to pass HTTP/S traffic to the remote proxy when acting as a forwarding server. When Eavesdrop is acting as a forwarder, it opens a remote connection with the proxy and passes everything to it without alteration of the original data. (Except by appending a 'Proxy-Authorization' header that tells it where to send its requests to)

**Comment by valloon427428** [comment]
Thanks
